---

########## GENERAL SETTINGS ######################################################################################################
name: tydom2mqtt
image: fmartinou/tydom2mqtt
version: 3.4.2.1
slug: tydom2mqtt
description: Deltadore Tydom to MQTT Bridge
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/VelJP/tydom2mqtt.git
services:
  - mqtt:need

########## DEFAULT OPTIONS #######################################################################################################
options:
  TYDOM_MAC: 001A25061766
  TYDOM_IP: 192.168.1.27
  TYDOM_PASSWORD: v|i%{wI89'ZO;|9
  TYDOM_ALARM_HOME_ZONE: 1
  TYDOM_ALARM_NIGHT_ZONE: 2
  MQTT_HOST: homeassistant
  MQTT_USER: VELAYGMQTT
  MQTT_PASSWORD: HomE0602
  MQTT_PORT: 1883
  MQTT_SSL: false
  LOG_LEVEL: INFO

########## OPTIONS SCHEMA ########################################################################################################
schema:
  LOG_LEVEL: list(DEBUG|INFO|WARNING|ERROR)?
  TYDOM_MAC: match(^001A25.*$)
  TYDOM_IP: str?
  TYDOM_PASSWORD: password
  TYDOM_ALARM_PIN: str?
  TYDOM_ALARM_HOME_ZONE: int?
  TYDOM_ALARM_NIGHT_ZONE: int?
  MQTT_HOST: str?
  MQTT_USER: str?
  MQTT_PASSWORD: password?
  MQTT_PORT: port?
  MQTT_SSL: bool?
  DELTADORE_LOGIN: str?
  DELTADORE_PASSWORD: password?
